package biblioConnect_v3;

public enum Permission {
    BORROW_BOOK, RETURN_BOOK, ADD_BOOK, REMOVE_BOOK, ADD_USER, REMOVE_USER, 
    GENERATE_REPORT, UPDATE_PROFILE, VIEW_ALL_USERS, VIEW_ALL_BOOKS
}